apiVersion: v1
kind: Service
metadata:
  name: s-api-rest-grpc
  namespace: project
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: main-deploy
    environment: develop
  type: ClusterIP
status:
  loadBalancer: {}

# 8100 mio es 8080 ejemplo
