apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: main-deploy
    environment: develop 
  name: d-api-rest-grpc
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-deploy
      environment: develop
  template:
    metadata:
      labels:
        app: main-deploy
        environment: develop
    spec:
      containers:
      - image: core.harbor.sopes/sopes1/clientgrpc
        name: clientgrpc
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "120Mi"
            cpu: "150m"
          limits:
            memory: "310Mi"
            cpu: "300m"
        env:
          - name: GRPC_CLIENT_HOST
            value: "0.0.0.0"
          - name: GRPC_CLIENT_PORT
            value: "8000"
          - name: GRPC_SERVER_HOST
            value: "0.0.0.0" 
          - name: GRPC_SERVER_PORT
            value: "8010"
          - name: RUST_SERVER_HOST
            value: "0.0.0.0"
          - name: RUST_SERVER_PORT
            value: "8020"
      - image: core.harbor.sopes/sopes1/servergrpc
        name: servergrpc
        ports:
          - containerPort: 8010
        resources:
          requests:
            memory: "120Mi"
            cpu: "150m"
          limits:
            memory: "310Mi"
            cpu: "300m"
        env:
          - name: KAFKA_SERVER_HOST
            value: "my-cluster-kafka-bootstrap.project.svc"
          - name: KAFKA_SERVER_PORT
            value: "9092"
          - name: GRPC_SERVER_HOST
            value: "0.0.0.0"
          - name: GRPC_SERVER_PORT
            value: "8010"
      - image: core.harbor.sopes/sopes1/redisclient
        name: redisclient
        ports:
          - containerPort: 8020
        resources:
          requests:
            memory: "120Mi"
            cpu: "150m"
          limits:
            memory: "310Mi"
            cpu: "300m"
        env:
          - name: RUST_SERVER_HOST
            value: "0.0.0.0"
          - name: RUST_SERVER_PORT
            value: "8020"
          - name: RUST_REDIS_HOST
            value: "sopesredis.project.svc"
          - name: RUST_REDIS_PORT
            value: "6379"
          - name: REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: user
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: password
      imagePullSecrets:
      - name: harbor-cred

# `my-cluster-kafka-bootstrap.project.svc:9092` if not `my-cluster-kafka-bootstrap-address:9092`
