apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjb3JlLmhhcmJvci5zb3BlcyI6eyJ1c2VybmFtZSI6InNvcGVzMSIsInBhc3N3b3JkIjoiOTUyLVdPcDBtdCIsImVtYWlsIjoiYm91cXVldC56b29tLjZoQGljbG91ZC5jb20iLCJhdXRoIjoiYzI5d1pYTXhPamsxTWkxWFQzQXdiWFE9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-cred
  namespace: project
type: kubernetes.io/dockerconfigjson
