apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjb3JlLmhhcmJvci5zb3BlcyI6eyJ1c2VybmFtZSI6InNvcGVzMSIsInBhc3N3b3JkIjoiOTUyLVdPcDBtJDd0IiwiZW1haWwiOiJib3VxdWV0Lnpvb20uNmhAaWNsb3VkLmNvbSIsImF1dGgiOiJjMjl3WlhNeE9qazFNaTFYVDNBd2JTUTNkQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-cred
  namespace: project
type: kubernetes.io/dockerconfigjson
