obj-m += cpu.o

all:
	make -C ../../../../../../../../lib/modules/$(shell uname -r) M='/mnt/c/Users/Juan Enrique/Sopes1/Lab/class4/RAM' modules

clean:
	make -C ../../../../../../../../lib/modules/$(shell uname -r) M='/mnt/c/Users/Juan Enrique/Sopes1/Lab/class4/RAM' clean