apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sopesredis
  name: sopesredis
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sopesredis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sopesredis
    spec:
      containers:
      - image: redis:8.0-M02-alpine3.20
        name: redis
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 6379
status: {}